import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { MenubarItems } from "@/lib/menubarItems";

const InterFont = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${InterFont.variable} antialiased flex flex-col min-w-screen justify-between relative`}
      >
        <nav className="absolute top-0 left-0 w-full bg-primary text-black">
          <div className="max-w-7xl mx-auto py-1 flex items-center justify-between">
          {MenubarItems?.map((item)=>(
            <Link href={'/'} key={item.id} className="text-black text-sm font-semibold">{item.name}</Link>
          ))}

          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
